project:
  type: website
  output-dir: docs

website:
  title: "Analisi dati interni"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: OIS
        menu:
          - href: OIS/progetti_propri.qmd
            text: Progetti Propri
          - href: OIS/bandi.qmd
            text: Bandi
      - text: SIME
        menu:
          - href: SIME/bandi.qmd
            text: Query sui bandi 2024/25

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true
